import os
import argparse
import subprocess
import sys

def create_project(name, stack):
    """
    Scaffolds a new project based on the selected stack.
    """
    print(f"[*] Initializing project '{name}' using stack '{stack}'...")
    
    try:
        if stack == "nextjs":
            # npx create-next-app@latest name --typescript --tailwind --eslint
            cmd = f"npx -y create-next-app@latest {name} --typescript --tailwind --eslint --no-src-dir --import-alias '@/*' --use-npm"
            subprocess.run(cmd, shell=True, check=True)
            
        elif stack == "vite":
            # npm create vite@latest name -- --template react-ts
            cmd = f"npm create vite@latest {name} -- --template react-ts"
            subprocess.run(cmd, shell=True, check=True)
            
            # Install dependencies immediately for Vite
            print("[*] Installing dependencies for Vite project...")
            subprocess.run(f"cd {name} && npm install", shell=True, check=True)
            
        elif stack == "html":
            os.makedirs(name, exist_ok=True)
            
            index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{name}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <main>
        <h1>Welcome to {name}</h1>
        <p>Generated by Antigravity Architect.</p>
    </main>
    <script src="app.js"></script>
</body>
</html>"""
            
            style_css = """body {
    font-family: system-ui, -apple-system, sans-serif;
    line-height: 1.5;
    max-width: 800px;
    margin: 0 auto;
    padding: 2rem;
    background: #f4f4f5;
    color: #18181b;
}"""
            
            app_js = "console.log('App initialized');"
            
            with open(os.path.join(name, "index.html"), "w", encoding="utf-8") as f:
                f.write(index_html)
            with open(os.path.join(name, "style.css"), "w", encoding="utf-8") as f:
                f.write(style_css)
            with open(os.path.join(name, "app.js"), "w", encoding="utf-8") as f:
                f.write(app_js)
                
        else:
            print(f"Error: Unknown stack '{stack}'.")
            return

        print(f"\n[+] Project '{name}' created successfully!")
        print(f"    Location: {os.path.abspath(name)}")
        
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Scaffold a new application project.")
    parser.add_argument("name", help="Name of the project directory")
    parser.add_argument("--stack", choices=["nextjs", "vite", "html"], default="html", help="Tech stack to use")
    
    args = parser.parse_args()
    create_project(args.name, args.stack)
